In [1]:
import numpy as np
import pandas as pd
import seaborn as sns

In [24]:
Process_Train = pd.read_csv("/home/felix/Desktop/dsn/train.csv", index_col=0)
Process_Test = pd.read_csv("/home/felix/Desktop/dsn/test.csv")
Process_Sample = pd.read_csv("/home/felix/Desktop/dsn/sample_submission2.csv")

In [25]:
Process_Train.dropna(axis=0,inplace=True)
Process_Train.isnull().sum()

Process_Test.dropna(axis=0,inplace=True)
Process_Test.isnull().sum()


EmployeeNo                             0
Division                               0
Qualification                          0
Gender                                 0
Channel_of_Recruitment                 0
Trainings_Attended                     0
Year_of_birth                          0
Last_performance_score                 0
Year_of_recruitment                    0
Targets_met                            0
Previous_Award                         0
Training_score_average                 0
State_Of_Origin                        0
Foreign_schooled                       0
Marital_Status                         0
Past_Disciplinary_Action               0
Previous_IntraDepartmental_Movement    0
No_of_previous_employers               0
dtype: int64

In [26]:
Process_Train_Categorical_Columns = ['Division', 'Qualification', 'Gender', 
                                     'Channel_of_Recruitment', 'State_Of_Origin',
                                     'Foreign_schooled', 'Marital_Status', 'Past_Disciplinary_Action',
                                     'Previous_IntraDepartmental_Movement']


In [10]:
for column in Process_Train_Categorical_Columns:
    print(column)
    print(Process_Train[column].value_counts())

Division
Commercial Sales and Marketing                 10599
Customer Support and Field Operations           7804
Sourcing and Purchasing                         5003
Information Technology and Solution Support     4890
Information and Strategy                        3491
Business Finance Operations                     1758
People/HR Management                            1682
Regulatory and Legal services                    729
Research and Innovation                          677
Name: Division, dtype: int64
Qualification
First Degree or HND         25578
MSc, MBA and PhD            10469
Non-University Education      586
Name: Qualification, dtype: int64
Gender
Male      25471
Female    11162
Name: Gender, dtype: int64
Channel_of_Recruitment
Agency and others                  20351
Direct Internal process            15478
Referral and Special candidates      804
Name: Channel_of_Recruitment, dtype: int64
State_Of_Origin
LAGOS          5942
FCT            2280
OGUN           2199
RIVE

In [15]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()
for column in Process_Train_Categorical_Columns:
    Process_Train[column] = label_encoder.fit_transform(Process_Train[column])
    print(column)
    print(Process_Train[column].unique())

Division
[1 2 4 3 8 0 5 7 6]
Qualification
[1 0 2]
Gender
[0 1]
Channel_of_Recruitment
[1 0 2]
State_Of_Origin
[ 3 20 26  2 13 30 24 28 23 11  4 34 18 31 12  7 16 19 32 14 27 15  9  6
 29  0 36 21  8  1 25 33 22 17  5 35 10]
Foreign_schooled
[0 1]
Marital_Status
[0 2 1]
Past_Disciplinary_Action
[0 1]
Previous_IntraDepartmental_Movement
[0 1]


In [27]:
Process_Train.head()

Division        Qualification  \
EmployeeNo                                                                
YAK/S/00001         Commercial Sales and Marketing     MSc, MBA and PhD   
YAK/S/00002  Customer Support and Field Operations  First Degree or HND   
YAK/S/00003         Commercial Sales and Marketing  First Degree or HND   
YAK/S/00004         Commercial Sales and Marketing  First Degree or HND   
YAK/S/00006               Information and Strategy  First Degree or HND   

             Gender   Channel_of_Recruitment  Trainings_Attended  \
EmployeeNo                                                         
YAK/S/00001  Female  Direct Internal process                   2   
YAK/S/00002    Male        Agency and others                   2   
YAK/S/00003    Male  Direct Internal process                   2   
YAK/S/00004    Male        Agency and others                   3   
YAK/S/00006    Male  Direct Internal process                   3   

             Year_of_birth  Last_performance_score  Year_of_recruitment  \
EmployeeNo                                                                
YAK/S/00001           1986                    12.5                 2011   
YAK/S/00002           1991                    12.5                 2015   
YAK/S/00003           1987                     7.5                 2012   
YAK/S/00004           1982                     2.5                 2009   
YAK/S/00006           1990                     7.5                 2012   

             Targets_met  Previous_Award  Training_score_average  \
EmployeeNo                                                         
YAK/S/00001            1               0                      41   
YAK/S/00002            0               0                      52   
YAK/S/00003            0               0                      42   
YAK/S/00004            0               0                      42   
YAK/S/00006            0               0                      77   

            State_Of_Origin Foreign_schooled Marital_Status  \
EmployeeNo                                                    
YAK/S/00001         ANAMBRA               No        Married   
YAK/S/00002         ANAMBRA              Yes        Married   
YAK/S/00003         KATSINA              Yes        Married   
YAK/S/00004           NIGER              Yes         Single   
YAK/S/00006       AKWA IBOM              Yes        Married   

            Past_Disciplinary_Action Previous_IntraDepartmental_Movement  \
EmployeeNo                                                                 
YAK/S/00001                       No                                  No   
YAK/S/00002                       No                                  No   
YAK/S/00003                       No                                  No   
YAK/S/00004                       No                                  No   
YAK/S/00006                       No                                  No   

            No_of_previous_employers  Promoted_or_Not  
EmployeeNo                                             
YAK/S/00001                        0                0  
YAK/S/00002                        0                0  
YAK/S/00003                        0                0  
YAK/S/00004                        1                0  
YAK/S/00006                        1                0

In [30]:
import sklearn
from sklearn import svm, preprocessing


In [31]:
Process_Train = sklearn.utils.shuffle(Process_Train)

In [36]:
X = Process_Train.drop("Promoted_or_Not", axis=1).values
y = Process_Train["Promoted_or_Not"].values

In [22]:
X_train = X[Process_Train]
y_train = y[Process_Train]

X_test = X[Process_Test]
y_test = y[Process_Test]

clf = svm.SVR(kernel="linear")
clf.fit()


array([['YAK/S/44587', 1, 1, ..., 0, 0, '1'],
       ['YAK/S/45779', 3, 0, ..., 0, 0, '3'],
       ['YAK/S/45334', 3, 1, ..., 0, 0, '1'],
       ...,
       ['YAK/S/07706', 7, 0, ..., 0, 0, '1'],
       ['YAK/S/41582', 2, 0, ..., 0, 0, '0'],
       ['YAK/S/35818', 1, 0, ..., 0, 0, '1']], dtype=object)